name: Terraform Validation

inputs:
  terraform-work-dir:
    description: 'Terraform working directory'
    required: false
    default: 'iac/tf'

runs:
  using: 'docker'
  image: docker://ghcr.io/augustinechiajh/terraform-tools:latest
  entrypoint: /bin/sh
  env:
    TERRAFORM_WORK_DIR: ${{ inputs.terraform-work-dir }}
  args:
    - "-c"
    - |
      set -euo pipefail
      export HOME=/root

      LOGFILE="/tmp/tf_ci_log_$(date +%Y%m%d%H%M%S).log"

      echo "## Starting Terraform CI Validation" | tee -a ${LOGFILE}

      if [ -z "${TERRAFORM_WORK_DIR}" ]; then
        echo "Error: 'terraform-work-dir' input is required but not set." | tee -a ${LOGFILE}
        exit 1
      fi

      if [ ! -d "${TERRAFORM_WORK_DIR}" ]; then
        echo "Error: Specified directory '${TERRAFORM_WORK_DIR}' does not exist or is not a directory." | tee -a ${LOGFILE}
        exit 1
      fi

      cd "${TERRAFORM_WORK_DIR}"
      
      echo "Running terraform fmt..." | tee -a ${LOGFILE}
      terraform fmt | tee -a ${LOGFILE}

      echo "Initializing terraform..." | tee -a ${LOGFILE}
      terraform init -backend=false | tee -a ${LOGFILE}

      echo "Validating terraform..." | tee -a ${LOGFILE}
      terraform validate | tee -a ${LOGFILE}

      echo "Initializing TFLint..." | tee -a ${LOGFILE}
      tflint --init | tee -a ${LOGFILE}

      echo "Running TFLint..." | tee -a ${LOGFILE}
      tflint | tee -a ${LOGFILE}

      echo "Terraform validation completed successfully." | tee -a ${LOGFILE}

      # Show summary in GitHub Actions UI
      echo "## Terraform CI Log" >> $GITHUB_STEP_SUMMARY
      cat $LOGFILE >> $GITHUB_STEP_SUMMARY